export const siteConfig = {
  name: "StartupNews.fyi",
  description: "Your source for startup news and stories",
  logo: "/logo.png",
  logoNav: "/logo.png",
  logoFoot: "/logo.png",
  copyright: "© Dotfyi Media Ventures Pvt Ltd",
  menu: [
    {
      label: "SECTORS",
      hasDropdown: true,
      children: [
        { label: "AI & Deeptech", href: "/ai-deeptech" },
        { label: "eCommerce", href: "/ecommerce" },
        { label: "EV & Mobility", href: "/ev-mobility" },
        { label: "Fintech", href: "/fintech" },
        { label: "Gaming", href: "/gaming" },
        { label: "Social Media", href: "/social-media" },
        { label: "Web3 & Blockchain", href: "/web3-blockchain" },
      ]
    },
    { label: "FUNDING TRACKER", href: "/funding" },
    { label: "EVENTS", href: "/events" },
    { label: "REPORTS" },
    { label: "AI", href: "/ai-deeptech" },
    { label: "ADVERTISE", href: "advertise-with-us/pagee" },
  ],
  footerMenu: [
    { label: "FUNDING TRACKER", href: "/funding" },
    { label: "EVENTS", href: "/events" },
    { label: "Entertainment", href: "/entertainment" },
    { label: "Business", href: "/business" },
    { label: "Tech", href: "/tech" },
    { label: "Privacy Policy", href: "/privacy-policy" },
    { label: "Terms and Conditions", href: "/terms-and-conditions" },
    { label: "Return and Refund Policy", href: "/return-refund-policy" },
  ],
  social: {
    facebook: "https://www.facebook.com/startupnews.fyi",
    twitter: "https://x.com",
    instagram: "https://www.instagram.com/startupnews.fyi/",
    youtube: "https://youtube.com",
    pinterest: "",
    tiktok: "",
    linkedin: "https://www.linkedin.com/company/startupnewsfyi",
    tumblr: "",
    googleplay: "/images/Google_Play-Logo.png",
    appstore: "/images/App_Store-Logo.png",
  },
  /** Fly-out (toggle) menu: expandable sections + simple links. id used for accordion state. */
  flyMenu: [
    {
      id: "sectors",
      label: "SECTORS",
      children: [
        { label: "AI & Deeptech", href: "/ai-deeptech" },
        { label: "Business", href: "/business" },
        { label: "Climate & Energy", href: "/climate-energy" },
        { label: "Consumer & D2C", href: "/consumer-d2c" },
        { label: "Cybersecurity", href: "/cybersecurity" },
        { label: "eCommerce", href: "/ecommerce" },
        { label: "EV & Mobility", href: "/ev-mobility" },
        { label: "Fintech", href: "/fintech" },
        { label: "Funding", href: "/funding" },
        { label: "Gaming", href: "/gaming" },
        { label: "Healthtech", href: "/healthtech" },
        { label: "Robotics", href: "/robotics" },
        { label: "SaaS & Enterprise", href: "/saas-enterprise" },
        { label: "Social Media", href: "/social-media" },
        { label: "Tech", href: "/tech" },
        { label: "Web3 & Blockchain", href: "/web3-blockchain" },

      ],
    },
    {
      id: "events",
      label: "EVENTS",
      href: "/events",
      children: [
        { label: "Dubai", href: "/events/dubai" },
        { label: "Delhi NCR", href: "/events/delhi-ncr" },
        { label: "Bengaluru", href: "/events/bengaluru" },
        { label: "Hyderabad", href: "/events/hyderabad" },
        { label: "Mumbai", href: "/events/mumbai" },
      ],
    },
    { label: "SUBMIT YOUR EVENT", href: "https://forms.gle/G4ZxCP3G1gTHJf1v5", dividerBefore: true },
    { label: "PARTNER WITH US" },
    {
      id: "press",
      label: "PRESS RELEASE",
      href: "/press",
      children: [{ label: "Submit", href: "https://forms.gle/FrCjzLGAs1gNaVyG7" }],
    },
    { label: "ADVERTISE WITH US", href: "advertise-with-us/pagee", dividerBefore: true },
    { label: "ABOUT US", href: "/about" },
    { label: "CONTACT US", href: "/contact-us" },
  ],
};
